### ISSUE TITLE
key-notions.md is not thorough

### ISSUE THREAD

**Issue by cogan-shimizu** [meganthehorse/CS7810#1]
Please see here for an example of desired style: https://github.com/CJMenart/MetadataRepresentationProject/blob/main/key-notions.md

Each Key Notion should be explicitly identified as such -- there is no way your only key-notion is asteroid. What about orbit? Isn't velocity important? etc.

If it is not clear what I'm asking for, please attend my office hour tomorrow, or organize a meeting with me on Thursday.

**Comment by threefinbdd** [comment]
Schema Diagram and Key-Notions are ready for review as of week of 3/13 Discussions and Feedback

**Comment by cogan-shimizu** [comment]
Much better. Good job.
