### ISSUE TITLE
Considerations for Moving Forward

### ISSUE THREAD

**Issue by cogan-shimizu** [meganthehorse/CS7810#15]
I just wanted to make sure to clarify some things -- and I realize that this could have been expressed a bit better within the confines of the course. Regardless, here are some considerations on moving forward with your particular knowledge graph project.

The purpose of the project is to -- overall -- construct, document, materialize, and utilize (in a minimal manner) a _good_ knowledge graph. "Good" can be defined in a couple of ways, within the context of this course. 

* It integrates many datasets to provide a holistic view of a domain or use-case
* It provides a good ontological representation of the phenomenological or domain discourse

From what I can tell of your datasets and competency questions -- the integration is really drawn from two different sources, and even then, it is primarily drawn from only one. There is nothing wrong with this _per se_, but as an educational outcome, it defeats the purpose of the project. If you have limited data, I would then dig into making sure that your schema is quite rich -- insofar that it provides an expressive and interesting view of the key notions beyond the "star patterns" that result from a 1:1 translation of tabular to knowledge graph relational representation.

I hope this helps think about the direction of your work for this project.

**Comment by Rmiller5466** [comment]
As you stated, our current approach does seem to boil down to just translating the tabular data to relational data.  This feedback has left me with a couple questions:  

- Do you recommend we go back to the competency questions and try to rethink the data we are collecting and what we are using the data for?   

- Do you think we may need to broaden our scope at all?  Our narrow focus on specific asteroids and asteroid properties for our use case seems to be the main issue with having so few data sources.

- Could you go in to more detail on what "making sure that your schema is quite rich" might entail in our case?  This question may relate to the previous one in reference to our current focus seeming to be fairly limited.

**Comment by cogan-shimizu** [comment]
> Do you recommend we go back to the competency questions and try to rethink the data we are collecting and what we are using the data for?

I would probably do a medium-strength search for additional data. I think this would be the most straightforward way to make your lives easier. For example, a quick search found this: (https://mp3c.oca.eu/) which you might be able to use to add some 1.1 million records.

> Do you think we may need to broaden our scope at all? Our narrow focus on specific asteroids and asteroid properties for our use case seems to be the main issue with having so few data sources.

Broadening your scope a little could help. I think that the asterank profitability has probably spoiled you, since I would have expected you to put together the constituent data yourselves. However, when I dug into trying to figure out how they did this, it's relatively opaque. Looks like a book from 1997 and some other non-peer reviewed sources. Perhaps digging into the data you would need to compute this number yourself would make for an interesting exercise. Additionally, you might look into modeling the heliocentric ecliptic coordinate system, which might be a better way of modeling location than "distance from the earth".

> Could you go in to more detail on what "making sure that your schema is quite rich" might entail in our case? This question may relate to the previous one in reference to our current focus seeming to be fairly limited.
In this case, I think you want to avoid a 1:1 translation of rows of a table of data into a knowledge graph. This generally results in what we call a "star pattern" since it's a relatively shallow (i.e., uninteresting) representation of the data.

Instead -- and by richer, I mean thinking about the features, properties, and characteristics of the things that you're recording. For example, think about provenance. These measurements are done according to whom? This is probably valuable knowledge to be able to ask your graph. It's not _your_ data. And secondly, you might consider that someone might find data that disagrees with yours. Providing a pointer back to where you took the data is always good. For example, see the PROV-O (provenance ontology) for some inspiration on that sort of modeling.

I hope this helps. Please continue to ask questions here, and I'll do my best to respond in a timely manner.

**Comment by threefinbdd** [comment]
PROV-O Insight provided by Cogan:
![image](https://user-images.githubusercontent.com/70174975/225091728-764ef250-51e3-4157-8e5a-128d71ae870f.png)
