### ISSUE TITLE
Meet with Cogan 3/28 about KG+TripleStore

### ISSUE THREAD

**Issue by threefinbdd** [meganthehorse/CS7810#20]
Next step process, what do we do?

**Comment by cogan-shimizu** [comment]
https://github.com/kastle-lab/cs7810-intro-to-ke/blob/master/project-deliverables/6-materialization.md

**Comment by threefinbdd** [comment]
Discuss to teammates minting and declaring individual URIs which *then* get their respective relationships to communicate together.

Individual minting of URI's allows for queries on just a "distance record" rather than the chain of events from asteroid-to-distancerecord. 

Example from Cogan:
```py
#  excluded init_kg and pfs intentionally for text size
with open("asteroid-distances.csv", "w") as f:
    lines = [line.strip() for line in f.readlines()[1:]]
    headers = lines[0].strip()

    for line in lines:
        asteroid_name, *distances = line

        # Mint the URI
        asteroid_uri = pfs["solr"][f"Asteroid.{asteroid_name}"]
        # Declare it
        graph.add( (asteroid_uri, a, pfs["sol"]["Asteroid"]) )

        for date, distance in zip(headers, distances):
            # Mint the DisRec URI
            distance_record_uri = pfs["solr"][f"DistanceRecord.{asteroid_name}.{date}"]
            # Declare it 
            graph.add( (distance_record_uri, a, pfs["sol"]["DistanceRecord"]) )
            # connect
            graph.add( () )

output_file = "output.ttl"
temp = graph.serialize(format="turtle", encoding="utf-8", destination=output_file)
```

**Comment by threefinbdd** [comment]
Questions and Answers for/by Cogan from Thursday:
1. Question usability of /resources/ and /ontology/ directory structure for name_space:
     ontology - schema, resources - instancesOf
2.  What makes good "naming conventions"?
     Unique but connected - 
3.  What prevents us from just modularizing our script into 1 python file from an instructor's perspective?
     Continuous Integration
4.  Should our prefixes reflect MODL or the parent namespace (such as a Quantity dervies from QUDT)
     Don't use parent namespaces. It can break from parent updates
