### ISSUE TITLE
axioms.md comments

### ISSUE THREAD

**Issue by cogan-shimizu** [meganthehorse/CS7810#21]
* in retrospect, numbering the axioms is probably a good idea.
* axiom 1: has -> is
* capitalize all concept names, including in the descriptions.
* double check that you understand `some` vs `only`. That is, the difference between a range restriction and an existential.
* there is at least one mismatch between cardinality in your descriptions and axioms

check these comments for each key notion/module.

**Comment by threefinbdd** [comment]
Group to meet at 6pm(ish) Wednesday 3/29 to discuss changes
