### ISSUE TITLE
Define Standard Naming Convention for Triplification

### ISSUE THREAD

**Issue by threefinbdd** [meganthehorse/CS7810#24]
Sample Triplification:
```
solr:Asteroid.Bennu a sol-ont:Asteroid,
        sosa:FeatureOfInterest ;
    sol-ont:hasDistanceRecord solr:DistanceRecord.Bennu.AUG23,
        solr:DistanceRecord.Bennu.AUG24, ...so on

solr:DistanceRecord.Bennu.AUG23 a sol-ont:DistanceRecord .

solr:DistanceRecord.Bennu.AUG24 a sol-ont:DistanceRecord .

solr:DistanceRecord.Bennu.AUG25 a sol-ont:DistanceRecord .

```
Should we consider a different syntax?

**Comment by cogan-shimizu** [comment]
Please do not consider a different syntax. I have approximately 0 interest in looking at anything except for Turtle.

**Comment by threefinbdd** [comment]
The comment is more focused on the concepts and entities represented as `DistanceRecord.Bennu.AUG25` if the group has a preference on how this should be read - not the actual Turtle output format.

**Comment by threefinbdd** [comment]
has Uniqueness + Of Just the Class Objects, does not extend up the chain

**Comment by threefinbdd** [comment]
Asteroid as a resource:  `CommonName` cannot be used (ryugu, bennu) as not all asteroids are "nicknamed".  Equally, a `Numerical Identification Number` is hard to address when we view the recently/newly discovered asteroids as they are (at the time of writing) simply referred to as their `DiscoveryName`.   We should opt to reference an asteroid's uri as their `DiscoveryName`.

The Numeric ID for SOL simply refers to the Provisional Designation Number described as:
* for unnamed minor planets: (number) [Provisional](https://en.wikipedia.org/wiki/Provisional_designation_in_astronomy) designation
* for [named minor planets](https://en.wikipedia.org/wiki/List_of_named_minor_planets_(numerical)): (number) Name; with or without parentheses

**Comment by threefinbdd** [comment]
URI Naming conventions discussed and addressed to Triplification on 4/4
