### ISSUE TITLE
Results Controlled Vocabulary

### ISSUE THREAD

**Issue by threefinbdd** [meganthehorse/CS7810#25]
- [ ] List QuantityKind; IE, "Velocity", "Distance", etc
- [ ] List of Unit; IE, "au", "kg", etc

**Comment by cogan-shimizu** [comment]
https://www.qudt.org/doc/DOC_VOCAB-QUANTITY-KINDS.html

**Comment by threefinbdd** [comment]
Declare a list of QK/Units in the schema.

**Comment by threefinbdd** [comment]
Asterank, Nasa, and MP3C Triplification uses identical CVs
