### ISSUE TITLE
Bullet Points from `documentation.md` for Powerpoint

### ISSUE THREAD

**Issue by threefinbdd** [meganthehorse/CS7810#40]
Hosted via WSU OneDrive
https://raidermailwright-my.sharepoint.com/:p:/g/personal/miller_1569_wright_edu/ER_Wr5T4sGNNgls4uUCr7JEBpdsq6od7T1Yn_9RTd9S41Q?e=TAT1Sc

**Comment by Rmiller5466** [comment]
Narrative - Megan, Brandon
Modules / Key Notions - Ryan
Powerpoint wrap up on 4/15

**Comment by Rmiller5466** [comment]
Reviewed slides, implemented finishing touches, created powerpoint pdf, divided slides up among us.
