### ISSUE TITLE
Schema re-design

### ISSUE THREAD

**Issue by Rmiller5466** [meganthehorse/CS7810#6]
Redesign schema based on in-class discussions and team meeting

**Comment by threefinbdd** [comment]
Requested input from Cogan on current diagram found on `schema-diagram.md`
https://github.com/meganthehorse/CS7810/blob/23585d73cefe0cba273df7c270390c6b74e53030/schema-diagrams/schema-diagram.md

**Comment by threefinbdd** [comment]
For discussion:  Are Asteroids a Feature of Interest:  
https://ci.mines-stetienne.fr/seas/FeatureOfInterestOntology

**Comment by threefinbdd** [comment]
For discussion: DistanceRecordings are Events with Temporal Extents.  Do we care to extrapolate more from individual Events and individual Temporal Extents?
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3583130

**Comment by threefinbdd** [comment]
Cogan to provide feedback provided context of CQ and dataset on 3/13
![Screenshot_20230311-125807](https://user-images.githubusercontent.com/70174975/224506772-66548992-5fe5-4681-856b-815b121783f1.png)

**Comment by threefinbdd** [comment]
Look at modl by Friday 8pm
Draft of schema by Saturday 12pm - Input by Saturday 5pm
Revisions on Sunday

Ryan to work on sub-properties of ObservableProperty (PhysicalProperty, OrbitalProperty, EconomicProperty)
Megan to work on DistanceRecord to reflect modl:Record
Brandon to work on PROV-O (CalculatedActivity:  AsteroidType)

Adjust "name" to a relationship with asteroid (hasName)

**Comment by threefinbdd** [comment]
Prior Notes from Cogan also in another issue:
![image](https://user-images.githubusercontent.com/70174975/226073078-7c9e0155-dfe9-46de-9c2a-d20ab94a109d.png)

Notes from Cogan 2/16:
SOSA:  Observation Pattern with Results including Quantity
![image](https://user-images.githubusercontent.com/70174975/226072922-e899a6e1-7d9f-46fe-a7fb-d6abb236bba4.png)

PROV-O using Observations
![image](https://user-images.githubusercontent.com/70174975/226072979-d23c4cc5-9d31-47a5-b411-facd016fce4d.png)

**Comment by threefinbdd** [comment]
Redesigned finalized and pushed with respect to patterns from MODL/Enslaved Ontology in mind
