### ISSUE TITLE
Finalize key-notions.md write up

### ISSUE THREAD

**Issue by Rmiller5466** [meganthehorse/CS7810#7]
Continue proofing and editing the key-notions document, adding changes from class discussion and team meetings

**Comment by threefinbdd** [comment]
Current draft requires review:
https://github.com/meganthehorse/CS7810/blob/42048b4cf9bf276524d8cb2699b78d511f171d17/Deliverables/key-notions.md

Personal feedback:  draft lacks counterpoints to discuss why we are *not* using existing patterns.  I loosely delve into why we shouldn't use Space Object Ontology for Asteroid, but we could be more explicit in the explanation.

**Comment by threefinbdd** [comment]
Addressed implementation of existing patterns in write up.

**Comment by threefinbdd** [comment]
Megan and Brandon re-word key-notions.
Megan to correct Asteroid Classification section by Monday 6PM Call.
